name: Run build on each commit
on: push
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Run Gradle build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build --info --stacktrace
    - name: Upload build reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: build-reports
        path: build/reports/
