name: Publish release
on:
  release:
    types: [ released ]
permissions:
  contents: write
jobs:
  build:
    name: Publish release
    runs-on: ubuntu-latest
    steps:

      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Setup Java toolchains
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: |
            8
            11
            17
            21

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Run Gradle build and publish artifacts
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build publish --info --stacktrace

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            build/docs/
            build/libs/
            build/reports/
            build/local-publish/

      - name: Publish docs
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: build/docs/javadoc/
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Gradle Plugin Portal
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishPlugins --info --stacktrace
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
